const problems = [
    {
        ProblemName: "1. Tổng hai số trong mảng",
        Difficulty: 1,
        DifficultyName: "Dễ",
        Topic: "Tính tổng",
        ProblemAccountState: 4,
        IsNew: true,
        Rate: 4.6,
        Comment: 15,
        Seen: 4052,
    },
    {
        ProblemName: "2. Sắp xếp mảng theo điều kiện",
        Difficulty: 3,
        DifficultyName: "Khó",
        Topic: "Sắp xếp",
        ProblemAccountState: 3,
        IsNew: true,
        Rate: 3.2,
        Seen: 75,
    },
    {
        ProblemName: "3. Giải mã kho báu",
        Difficulty: 2,
        DifficultyName: "Vừa",
        ProblemAccountState: 1,
        Rate: 5,
        Comment: 1200,
        Seen: 28000,
    },
    {
        ProblemName: "4. Đi để trở về",
        Difficulty: 3,
        DifficultyName: "Khó",
        Topic: "Chuỗi",
        ProblemAccountState: 2,
        Rate: 4.3,
        Comment: 102,
        Seen: 120,
    },
    {
        ProblemName: "5. Giải phương trình bậc 3",
        Difficulty: 2,
        DifficultyName: "Vừa",
        Rate: 4.4,
        Comment: 52,
        Seen: 103,
    },
    {
        ProblemName: "6. Chuỗi fibonacci",
        Difficulty: 1,
        DifficultyName: "Dễ",
        Topic: "Chuỗi",
        ProblemAccountState: 4,
        Rate: 4.7,
        Comment: 1023,
        Seen: 12035,
    },
    {
        ProblemName: "7. TÌm giới hạn hàm số",
        Difficulty: 2,
        DifficultyName: "Vừa",
        Topic: "Toán",
        ProblemAccountState: 1,
        Rate: 3.9,
        Comment: 12,
        Seen: 302,
    },
    {
        ProblemName: "8. Cộng thời gian",
        Difficulty: 1,
        DifficultyName: "Dễ",
        Topic: "OOP",
        Rate: 4.2,
        Comment: 10,
        Seen: 45,
    },
];
export default problems;
